version: '3.7'
services:
  server:
    build:
      context: .
      dockerfile: cmd/Dockerfile
    container_name: srv
    env_file:
      - config/.env
    environment:
      - STORAGE_FLAG
    ports:
      - '8080:8080'

  db:
    image: postgres:15.5-alpine3.18
    restart: always
    env_file:
      - config/.env
    ports:
        - '5432:5432'

  redis:
    image: redis:alpine
    restart: always
    env_file:
          - config/.env
    ports:
      - '6379:6379'

