openapi: '3.0.2'
info:
  title: URL Shortener
  version: '1.0.0'
  description:
    URL shortening service enabling to shorten long URLs into eight-character codes - short URLs that redirect to original, longer ones.

servers:
  - url: http://localhost:8080

paths:
  /:
    post:
      summary: get alias
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/url"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/alias"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorMessage"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /{alias}:
    get:
      summary: get original URL
      parameters:
        - $ref: "#/components/schemas/url"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/url"
        '401':
          description: Unauthorized
        '404':
          description: Not Found

components:
  schemas:
    errorMessage:
      type: object
      properties:
        errorType:
          type: string
          enum: [Validation, Conflict]
        body:
          type: string

    url:
      description: original URL
      format:
      type: string

    alias:
      description: shorten URL
      type: string
      minLength: 8
      maxLength: 8
