openapi: '3.0.2'
info:
  title: URL Shortener
  version: '1.0.0'
  description:
    URL shortening service enabling to shorten long URLs into eight-character codes - short URLs that redirect to original, longer ones.

servers:
  - url: http://localhost:8080

paths:
  /:
    post:
      summary: create alias
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/url"
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/alias"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: string
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: string
  /{alias}:
    get:
      summary: get original URL
      parameters:
        - $ref: "#/components/schemas/alias"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/url"
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: string

components:
  schemas:
    url:
      description: original URL
      type: string
    alias:
      description: shorten URL
      type: string
      minLength: 8
      maxLength: 8
